services:
  - type: web
    name: portal-assinaturas-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      # O Render já define automaticamente a variável $PORT, não é necessário configurá-la
      # Mas se quiser definir outras variáveis, adicione-as abaixo:
      # - key: DATABASE_URL
      #   value: sua_string_de_conexao
