services:
  - type: web
    name: portal-assinaturas-backend
    env: python
    region: oregon
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT  # Alterado para usar a variável $PORT
    plan: free
    envVars:
      - key: PORT
        # Remover esse valor, pois o Render já define a porta automaticamente
